# use base image
FROM codecasts/php-alpine:base

# Projects's maintainer
MAINTAINER Diego Hernandes <diego@hernandev.com>

USER root

ADD php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN echo "/home/sandbox/packages/7.1" >> /etc/apk/repositories

USER sandbox

