name: "alpine-v3.12"

# workflow env.
env:
  ALPINE_VERSION: "3.12"
  APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
  APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
  BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

on:
  push:
    branches:
      - publish
      - master

jobs:
  build-php-8-0:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: ${{ matrix.php.version }}
      PHP_MINOR_VERSION: ${{ matrix.php.release }}

    strategy:
      matrix:
        php:
          - version: "8.0"
            release: "8.0.0"
          - version: "7.4"
            release: "7.4.13"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: debug-info
        run: |
          echo -e "Job strategy: "
          echo -e "Alpine Linux: v${{ env.ALPINE_VERSION }}"
          echo -e "PHP Version: ${{ env.PHP_VERSION }}"
          echo -e "PHP Release: ${{ env.PHP_MINOR_VERSION }}"
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: alpine-v${{ env.ALPINE_VERSION }}-php-${{ env.PHP_MINOR_VERSION }}
          path: repo/*-${{ env.ALPINE_VERSION }}/*-${{ env.PHP_MINOR_VERSION }}
      - name: build
        run: |
          echo "" > .env
          echo -e "${{ secrets.PHP_ALPINE_RSA }}" > .abuild/php-alpine.rsa
          echo -e "${{ secrets.PHP_ALPINE_RSA_PUB }}" > .abuild/php-alpine.rsa.pub
          ./build.sh build
          echo -e "bash publish.sh"
