# workflow name.
name: build-aarch64

# workflow env.
env:
  DOCKER_BUILDKIT: 1
  APORTS_SCRIPTS: /home/sandbox/scripts
  APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
  APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
  BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
on:
  push:
    branches:
      - master
      - publish

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      DOCKER_PLATFORM: linux/arm64
      ALPINE_ARCH: ${{ matrix.arch }}
      ALPINE_VERSION: ${{ matrix.alpine }}
      PHP_VERSION: ${{ matrix.php }}
      PHP_MINOR_VERSION: ${{ matrix.release }}
      ALPINE_VERSION_SLUG: v${{ matrix.alpine }}
      PHP_VERSION_SLUG: php-${{ matrix.php }}
      PA_ARCH: ${{ matrix.arch }}
      PA_BUILD_SLUG: v${{ matrix.alpine }}_php-${{ matrix.php }}_${{ matrix.arch }}
      PA_BUILD_PATH: repo/v${{ matrix.alpine }}/php-${{ matrix.php }}/${{ matrix.arch }}

    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        include:
          # alpine-v3.14-php-8.1
          - alpine: "3.14"
            php: "8.1"
            release: "8.1.0"
            arch: "aarch64"
          # alpine-v3.14-php-8.0
          - alpine: "3.14"
            php: "8.0"
            release: "8.0.13"
            arch: "aarch64"

          # alpine-v3.13-php-8.1
          - alpine: "3.13"
            php: "8.1"
            release: "8.1.0"
            arch: "aarch64"
          # alpine-v3.13-php-8.0
          - alpine: "3.13"
            php: "8.0"
            release: "8.0.13"
            arch: "aarch64"

          # alpine-v3.12-php-8.1
          - alpine: "3.12"
            php: "8.1"
            release: "8.1.0"
            arch: "aarch64"
          # alpine-v3.12-php-8.0
          - alpine: "3.12"
            php: "8.0"
            release: "8.0.13"
            arch: "aarch64"
          # alpine-v3.12-php-7.4
          - alpine: "3.12"
            php: "7.4"
            release: "7.4.26"
            arch: "aarch64"

          # alpine-v3.11-php-8.0
          - alpine: "3.11"
            php: "8.0"
            release: "8.0.13"
            arch: "aarch64"
          # alpine-v3.11-php-7.4
          - alpine: "3.11"
            php: "7.4"
            release: "7.4.26"
            arch: "aarch64"
          # alpine-v3.11-php-7.3
          - alpine: "3.11"
            php: "7.3"
            release: "7.3.33"
            arch: "aarch64"

          # alpine-v3.10-php-7.4
          - alpine: "3.10"
            php: "7.4"
            release: "7.4.26"
            arch: "aarch64"
          # alpine-v3.10-php-7.3
          - alpine: "3.10"
            php: "7.3"
            release: "7.3.33"
            arch: "aarch64"

    steps:
      # checkout repository.
      - name: git-checkout
        uses: actions/checkout@v2

      # cache packages.
      - name: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PA_BUILD_PATH }}
          key: ${{ env.PA_BUILD_SLUG }}-${{ hashFiles('scripts/**/APKBUILD') }}
          restore-keys: |
            ${{ env.PA_BUILD_SLUG }}-${{ hashFiles('scripts/**/APKBUILD') }}
            ${{ env.PA_BUILD_SLUG }}-
            ${{ env.PA_BUILD_SLUG }}

      # debug info.
      - name: debug-info
        run: |
          echo -e "Job strategy: "
          echo -e "Alpine Linux: v${{ env.ALPINE_VERSION }}"
          echo -e "PHP Version: ${{ env.PHP_VERSION }}"
          echo -e "PHP Release: ${{ env.PHP_MINOR_VERSION }}"

      # build packages.
      - name: build
        uses: uraimo/run-on-arch-action@master
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
            uname -a
            export DEBIAN_FRONTEND=noninteractive
            whoami
            apt update -y
            apt install -y curl
          run: |
            echo "" > .env
            echo -e "${{ secrets.PHP_ALPINE_RSA }}" > .abuild/php-alpine.rsa
            echo -e "${{ secrets.PHP_ALPINE_RSA_PUB }}" > .abuild/php-alpine.rsa.pub
            docker compose run sandbox buildrepo -a ${{ env.APORTS_SCRIPTS }} -p ${{ env.PHP_VERSION_SLUG }}

      # upload artifacts.
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PA_BUILD_SLUG }}
          path: ${{ env.PA_BUILD_PATH }}

      - name: deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr
          path: repo/
          remote_path: ${{ secrets.RSYNC_TARGET }}
          remote_host: ${{ secrets.RSYNC_HOST }}
          remote_user: ${{ secrets.RSYNC_USER }}
          remote_key: ${{ secrets.RSYNC_KEY }}