# workflow name.
name: build-aarch64

# workflow env.
env:
  DOCKER_BUILDKIT: 1
  APORTS_SCRIPTS: /home/sandbox/scripts
  APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
  APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
  BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
on:
  push:
    branches:
      - master
      - publish

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      DOCKER_PLATFORM: linux/arm64
      DOCKER_DISTRO: ubuntu18.04
      ALPINE_ARCH: ${{ matrix.arch }}
      ALPINE_VERSION: ${{ matrix.alpine }}
      PHP_VERSION: ${{ matrix.php }}
      ALPINE_VERSION_SLUG: v${{ matrix.alpine }}
      PHP_VERSION_SLUG: php-${{ matrix.php }}
      PA_ARCH: ${{ matrix.arch }}
      PA_BUILD_SLUG: v${{ matrix.alpine }}_php-${{ matrix.php }}_${{ matrix.arch }}
      PA_BUILD_PATH: repo/v${{ matrix.alpine }}/php-${{ matrix.php }}/${{ matrix.arch }}

    strategy:
      fail-fast: false
      #max-parallel: 2
      matrix:
        include:
          # alpine-v3.15-php-8.1
          - alpine: "3.15"
            php: "8.1"
            release: "8.1.1"
            arch: "aarch64"
          # alpine-v3.15-php-8.0
          - alpine: "3.14"
            php: "8.0"
            release: "8.0.14"
            arch: "aarch64"
          # alpine-v3.14-php-8.1
          - alpine: "3.14"
            php: "8.1"
            release: "8.1.1"
            arch: "aarch64"
          # alpine-v3.14-php-8.0
          - alpine: "3.14"
            php: "8.0"
            release: "8.0.14"
            arch: "aarch64"

          # alpine-v3.13-php-8.1
          - alpine: "3.13"
            php: "8.1"
            release: "8.1.1"
            arch: "aarch64"
          # alpine-v3.13-php-8.0
          - alpine: "3.13"
            php: "8.0"
            release: "8.0.14"
            arch: "aarch64"

          # alpine-v3.12-php-8.1
          - alpine: "3.12"
            php: "8.1"
            release: "8.1.1"
            arch: "aarch64"
          # alpine-v3.12-php-8.0
          - alpine: "3.12"
            php: "8.0"
            release: "8.0.27"
            arch: "aarch64"
          # alpine-v3.12-php-7.4
          - alpine: "3.12"
            php: "7.4"
            release: "7.4.26"
            arch: "aarch64"

          # alpine-v3.11-php-8.0
          - alpine: "3.11"
            php: "8.0"
            release: "8.0.14"
            arch: "aarch64"
          # alpine-v3.11-php-7.4
          - alpine: "3.11"
            php: "7.4"
            release: "7.4.26"
            arch: "aarch64"
          # alpine-v3.11-php-7.3
          - alpine: "3.11"
            php: "7.3"
            release: "7.3.33"
            arch: "aarch64"

          # alpine-v3.10-php-7.4
          - alpine: "3.10"
            php: "7.4"
            release: "7.4.26"
            arch: "aarch64"
          # alpine-v3.10-php-7.3
          - alpine: "3.10"
            php: "7.3"
            release: "7.3.33"
            arch: "aarch64"

    steps:
      # checkout repository.
      - name: git-checkout
        uses: actions/checkout@v2

      # cache packages.
      - name: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PA_BUILD_PATH }}
          key: ${{ env.PA_BUILD_SLUG }}-${{ hashFiles('scripts/**/APKBUILD') }}
          restore-keys: |
            ${{ env.PA_BUILD_SLUG }}-${{ hashFiles('scripts/**/APKBUILD') }}
            ${{ env.PA_BUILD_SLUG }}-
            ${{ env.PA_BUILD_SLUG }}

      # debug info.
      - name: debug-info
        run: |
          echo -e "Job strategy: "
          echo -e "Alpine Linux: v${{ env.ALPINE_VERSION }}"
          echo -e "PHP Version: ${{ env.PHP_VERSION }}"

      # rsync download.
      - uses: up9cloud/action-rsync@v1.3
        name: rsync-download
        env:
          HOST: ${{ secrets.RSYNC_HOST }}
          USER: ${{ secrets.RSYNC_USER }}
          KEY: ${{ secrets.RSYNC_KEY }}
          SOURCE: ${{ secrets.RSYNC_TARGET }}/
          TARGET: ./repo/
          MODE: pull
          VERBOSE: true

      - name: prepare
        run: |
          ls -lhart repo/
          echo -e "${{ secrets.PHP_ALPINE_RSA }}" > .abuild/php-alpine.rsa
          echo -e "${{ secrets.PHP_ALPINE_RSA_PUB }}" > .abuild/php-alpine.rsa.pub

      # build packages.
      - name: build
        uses: uraimo/run-on-arch-action@v2
        with:
          env: |
            DOCKER_BUILDKIT: 1
            DOCKER_PLATFORM: ${{ env.DOCKER_PLATFORM }}
            ALPINE_VERSION: "${{ env.ALPINE_VERSION }}"
            PHP_VERSION: ${{ env.PHP_VERSION }}
            PHP_VERSION_SLUG: ${{ env.PHP_VERSION_SLUG }}
            APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
            APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
          arch: ${{ matrix.arch }}
          distro: ${{ env.DOCKER_DISTRO }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --privileged --platform=${{ env.DOCKER_PLATFORM }}
          install: |
            mount
            env
            uname -a
            export DEBIAN_FRONTEND=noninteractive
            whoami
            apt update -y
            apt install -y curl
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            docker --version
            mkdir -p ~/.docker/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-aarch64 -o ~/.docker/cli-plugins/docker-compose
            chmod +x ~/.docker/cli-plugins/docker-compose
            docker compose version
          run: |
            mount
            env
            docker run --platform=$DOCKER_PLATFORM -it --rm alpine:3.15 uname -a
            echo "" > .env
            docker compose run sandbox buildrepo -p -a /home/sandbox/scripts $PHP_VERSION_SLUG

      # upload artifacts.
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PA_BUILD_SLUG }}
          path: ${{ env.PA_BUILD_PATH }}

      - name: deploy
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr
          path: repo/
          remote_path: ${{ secrets.RSYNC_TARGET }}
          remote_host: ${{ secrets.RSYNC_HOST }}
          remote_user: ${{ secrets.RSYNC_USER }}
          remote_key: ${{ secrets.RSYNC_KEY }}