name: build-php-7-4

# workflow env.
env:
  APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
  APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
  BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  PHP_VERSION: "7.4"
  PHP_MINOR_VERSION: "7.4.13"

on:
  push:
    branches:
      - publish

jobs:
  build-php-7-4:
    runs-on: ubuntu-latest

    env:
      ALPINE_VERSION: ${{ matrix.alpine }}
      BUILD_OUTPUT_DIR: repo/v${{ matrix.alpine }}/php-${{ env.PHP_VERSION }}
      BUILD_ARTIFACT_NAME: alpine-v${{ env.ALPINE_VERSION }}-php-${{ env.PHP_MINOR_VERSION }}

    strategy:
      matrix:
        alpine: [ "3.12", "3.11", "3.10" ]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: |
          echo "" > .env
          echo -e "${{ secrets.PHP_ALPINE_RSA }}" > .abuild/php-alpine.rsa
          echo -e "${{ secrets.PHP_ALPINE_RSA_PUB }}" > .abuild/php-alpine.rsa.pub
          ./build.sh build
          echo -e "bash publish.sh"
      - name: compress
        uses: papeloto/action-zip@v1
        with:
          files: ${{ env.BUILD_OUTPUT_DIR }}
          recursive: true
          dest: ${{ env.BUILD_ARTIFACT_NAME }}.zip
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_NAME }}.zip
