name: build-php-7-3

# workflow env.
env:
  APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
  APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
  BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
  BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  PHP_VERSION: "7.3"
  PHP_MINOR_VERSION: "7.3.25"

on:
  push:
    branches:
      - publish
      # - master

jobs:
  build-php-7-3:
    runs-on: ubuntu-latest

    env:
      ALPINE_VERSION: ${{ matrix.alpine }}

    strategy:
      matrix:
        alpine: [ "3.11", "3.10" ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: build
        run: |
          echo "" > .env
          echo -e "${{ secrets.PHP_ALPINE_RSA }}" > .abuild/php-alpine.rsa
          echo -e "${{ secrets.PHP_ALPINE_RSA_PUB }}" > .abuild/php-alpine.rsa.pub
          ./build.sh build
          echo -e "bash publish.sh"
      - name: compress
        uses: papeloto/action-zip@v1
        with:
          files: repo/v${{ matrix.alpine }}/php-${{ env.PHP_VERSION }}
          recursive: true
          dest: alpine-v${{ matrix.alpine }}-php-${{ env.PHP_MINOR_VERSION }}.zip
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: alpine-v${{ matrix.alpine }}-php-${{ env.PHP_MINOR_VERSION }}
          path: alpine-v${{ matrix.alpine }}-php-${{ env.PHP_MINOR_VERSION }}.zip
